### ISSUE TITLE
Completion menu function signature pop up not working

### ISSUE THREAD

**Issue by danielnehrig** [hrsh7th/nvim-compe#350]
#### Describe the bug

When Autocompletion Triggers
and i press ctrl+n to go to the next item in list no function information/signature pop up is displayed
when i press ctrl+p and the again ctrl+n to go back to the same autocompletion it will show the signature (see attached video at the bottom)

#### To Reproduce
Steps to reproduce the behavior with the [config](https://github.com/danielnehrig/.dotfiles-darwin/tree/master/.config/nvim):

1. Go to Source code
2. enter a function item
3. wait for LSP to load and index functions
4. select wanted function name from triggered autocompletion

#### Actual behaviour

When selecting a auto completion item the signature pop up is not triggered only on the second time selecting
the same completion item

#### Expected behaviour

When selecting a auto completion item the signature pop up triggers on first selection of function

#### Video
[Video link](https://streamable.com/3lbvxi)

**Comment by danielnehrig** [comment]
On further investigation it looks like this is only happening with TS LSP
Rust analyzer working fine and LUA LSP working fine as well

**Comment by fnune** [comment]
Can confirm that this works fine with Pyright, but not on Typescript Language Server.

The behavior is exactly like the OP describes: the first time one selects an option, the `resolve` floating popup doesn't appear:

![image](https://user-images.githubusercontent.com/16181067/121612536-d8513480-ca5a-11eb-90b6-eb4a5cbc51bf.png)

However, after moving to another option and coming back:

![image](https://user-images.githubusercontent.com/16181067/121612571-ea32d780-ca5a-11eb-95bd-db13e11cdf6a.png)

This is reproducible with the rest of the options. They all work on the second go.

**Comment by fnune** [comment]
@hrsh7th It works great now!

Thank you so much :tada:

**Comment by VVKot** [comment]
@hrsh7th @fnune is there some specific config that I need for this to work? Still not getting anything for Typescript. Here's my compe config:

https://github.com/VVKot/dotfiles/blob/3d7672a74564dcafb18ab8649c59715cd901c4f4/config/nvim/lua/plugin/lsp.lua#L31-L53

**Comment by fnune** [comment]
@VVKot I only just started learning this myself. But I pushed a WIP branch of my dotfiles where I'm testing Neovim's native LSP. Here it is, if you want to take a look: https://github.com/fnune/dotfiles/blob/wip-native-lsp/neovim/.config/nvim/plugins.vim#L315

**Comment by VVKot** [comment]
@hrsh7th hmmm, can confirm that is seems to be OS/something related to that problem. I am using the same config, same Typescript repository to repro. Both machines are on latest Neovim commit to date - https://github.com/neovim/neovim/commit/141647cfbb1f137e3eefe6ba8e658b475e902cac, however, on MacOS I am getting all resolved completion items, and on Ubuntu - only some, like 20% of them. It does not seem to be a timing problem since just waiting for function signature pop up to appear does nothing on Ubuntu.

1. Any tips on how to debug that?
2. Maybe you have a repro somewhere that you used, so that I can verify on it with both of my setups?

**Comment by hrsh7th** [comment]
I will re-check it.

**Comment by VVKot** [comment]
Thanks @hrsh7th! Sadly `resolve_timeout` does not seem to fix the problem for me. I also tried increasing to ridiculous numbers, e.g. 10 sec - I am still hitting the same behavior. I.e. for some completions (always the same ones) I do get function signature/auto import description, and for other ones I don't. Any logs/anything else that I should check out?

**Comment by hrsh7th** [comment]
Hm... Your problem seems like the language-server's problem to me.

You can check `~/.cache/nvim/lsp.log` maybe.

**Comment by VVKot** [comment]
Hmmm, no idea what happened here, but after some combination of recompiling/updating my neovim/updating plugins/switching branches this problem went away. I now have correct function signature popups on both machines. Thanks again for the blazingly fast fixes! ❤️

**Comment by danielnehrig** [comment]
i just wanted to confirm that the original issue i opened is also solved from my side
thanks for the work @hrsh7th
